export const ADD_PRODUCT_TO_CART = "ADD_PRODUCT_TO_CART"
export const REMOVE_ITEMS_FROM_CART = "REMOVE_ITEMS_FROM_CART"
export const UPDATE_CART_TOTAL_PRICE = "UPDATE_CART_TOTAL_PRICE"
export const REMOVE_ALL_CART_ITEMS = "REMOVE_ALL_CART_ITEMS"